[package]
name = "vitype_core"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

[lib]
name = "vitype_core"
crate-type = ["staticlib", "cdylib"]

[dependencies]
once_cell = "1.21.3"
unicode-normalization = "0.1"
